/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import control.InfraccionJpaController;
import control.InfraccionesJpaController;
import control.TipovehiculoJpaController;
import control.VehiculoJpaController;
import control.exceptions.NonexistentEntityException;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import modelo.Infraccion;
import modelo.Infracciones;
import modelo.TModeloInfraccion;
import modelo.TModeloPagoInfracciones;
import modelo.TModeloVehiculo;
import modelo.Tipovehiculo;
import modelo.Vehiculo;

public class UIPagoInfraccion extends javax.swing.JFrame {

    private InfraccionesJpaController cInfracciones;
    private VehiculoJpaController cvehiculo;
    private Vehiculo vehiculo;
    private Infracciones infracciones;
    private List<Vehiculo> Lista_vehiculos;
    private List<Infracciones> Lista_Infracciones;
    private TModeloPagoInfracciones modeloPago;
    private ArrayList idVehiculo=new ArrayList();

    public UIPagoInfraccion() {
        initComponents();
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("1ProyectoVehiculoPU");
        cInfracciones = new InfraccionesJpaController(emf);
        cvehiculo = new VehiculoJpaController(emf);
        Lista_Infracciones = cInfracciones.findInfraccionesEntities();
        Lista_vehiculos = cvehiculo.findVehiculoEntities();
        modeloPago = new TModeloPagoInfracciones(Lista_Infracciones);
        modeloPago.fireTableDataChanged();
        tablaPagos.setModel(modeloPago);
        cargarVehiculo();
        
    }
    
    private void cargarVehiculo() {
                Lista_vehiculos = cvehiculo.findVehiculoEntities();
                combo_vehiculo.removeAllItems();
                combo_vehiculo.addItem(".");
                idVehiculo.add("0");
                for (Vehiculo vh:Lista_vehiculos) {
                       combo_vehiculo.addItem(vh.getPlaca());
                       idVehiculo.add(vh.getIdve());
                }
        }
    private void mostrarTabla()
    {
        modeloPago = new TModeloPagoInfracciones(Lista_Infracciones);
        modeloPago.setIdVehiculo((int) idVehiculo.get(combo_vehiculo.getSelectedIndex()));
        modeloPago.fireTableDataChanged();
        tablaPagos.setModel(modeloPago);
    }
    private void mostrarTotal()
    {
        double suma=0;
        for (int i = 0; i < tablaPagos.getRowCount(); i++) {
            double monto=Double.parseDouble((String) tablaPagos.getValueAt(i, 2));
            suma+=monto;
        }
        txt_montoTotal.setText(""+suma);
    }
    private void agregarPago() {
        try {
            Date fechaPago = ParseFecha(txt_fecha.getText());
            int datos = tablaPagos.getSelectedRowCount();
            double total = 0;
            if (datos == 0) {
                for (int i = 0; i < tablaPagos.getRowCount(); i++) {
                    int folioInf = (int) tablaPagos.getValueAt(i, 0);
                    editarFechaPago(folioInf, fechaPago);
                }
            } else {
                int[] datoss = tablaPagos.getSelectedRows();
                for (int i = 0; i < datos; i++) {
                    int folioInf = (int) tablaPagos.getValueAt(datoss[i], 0);
                    editarFechaPago(folioInf, fechaPago);
                }
            }
        } catch (Exception e) {
            System.out.println("Error al agregar pago: " + e.getMessage());
        }
    }

    private void editarFechaPago(int folioInf, Date fechaPago) {
    try {
        Infracciones infraccion = cInfracciones.findInfracciones(folioInf);
        if (infraccion != null) {
            infraccion.setFechapago(fechaPago);
            cInfracciones.edit(infraccion);
        }
    } catch (NonexistentEntityException ex) {
        System.out.println("Infraccion no encontrada: " + folioInf);
    } catch (Exception ex) {
        System.out.println("Error al editar infraccion: " + ex.getMessage());
    }
}

    public static Date ParseFecha(String fecha) {
        SimpleDateFormat formato = new SimpleDateFormat("yyyy/MM/dd");
        Date fechaDate = null;
        try {
            fechaDate = formato.parse(fecha);
        } catch (ParseException ex) {
            System.out.println(ex);
        }
        return fechaDate;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        combo_vehiculo = new Herramientas.Combobox();
        panelRound4 = new Herramientas.PanelRound();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPagos = new javax.swing.JTable();
        txt_montoTotal = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panelRound3 = new Herramientas.PanelRound();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_fecha = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(32, 32, 32));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, 40, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(248, 248, 248));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("PAGO DE INFRACCIONES");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 370, -1));

        combo_vehiculo.setBackground(new java.awt.Color(34, 34, 34));
        combo_vehiculo.setForeground(new java.awt.Color(248, 248, 248));
        combo_vehiculo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", " " }));
        combo_vehiculo.setSelectedIndex(-1);
        combo_vehiculo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        combo_vehiculo.setLabeText("Vehiculo");
        combo_vehiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                combo_vehiculoMouseClicked(evt);
            }
        });
        combo_vehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_vehiculoActionPerformed(evt);
            }
        });
        jPanel1.add(combo_vehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 190, 50));

        panelRound4.setBackground(new java.awt.Color(54, 54, 54));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(248, 248, 248));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Descripción");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(248, 248, 248));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("No. Infracción");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(248, 248, 248));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Monto");

        javax.swing.GroupLayout panelRound4Layout = new javax.swing.GroupLayout(panelRound4);
        panelRound4.setLayout(panelRound4Layout);
        panelRound4Layout.setHorizontalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        panelRound4Layout.setVerticalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 350, 30));

        tablaPagos.setBackground(new java.awt.Color(64, 64, 64));
        tablaPagos.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        tablaPagos.setForeground(new java.awt.Color(248, 248, 248));
        tablaPagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"a", "1", null},
                {"b", "2", null},
                {"c", "3", null},
                {"d", "4", null},
                {"e", "5", null},
                {"r", "6", null},
                {"f", "7", null},
                {"g", "8", null},
                {"h", "9", null},
                {"i", "0", null},
                {"j", "1", null},
                {"k", "2", null},
                {null, null, null}
            },
            new String [] {
                "", "", ""
            }
        ));
        tablaPagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPagosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaPagos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 350, 210));

        txt_montoTotal.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt_montoTotal.setForeground(new java.awt.Color(248, 248, 248));
        txt_montoTotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txt_montoTotal.setText("000.00");
        txt_montoTotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_montoTotalMouseClicked(evt);
            }
        });
        jPanel1.add(txt_montoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 120, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(248, 248, 248));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Monto total:");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 120, 30));

        panelRound3.setBackground(new java.awt.Color(64, 64, 64));
        panelRound3.setRoundBottomLeft(30);
        panelRound3.setRoundBottomRight(30);
        panelRound3.setRoundTopLeft(30);
        panelRound3.setRoundTopRight(30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(248, 248, 248));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Pagar");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel1.add(panelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 110, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/antes.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 40, 40));

        txt_fecha.setBackground(new java.awt.Color(248, 248, 248));
        txt_fecha.setForeground(new java.awt.Color(8, 8, 8));
        txt_fecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_fecha.setBorder(null);
        txt_fecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_fechaKeyPressed(evt);
            }
        });
        jPanel1.add(txt_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 110, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(248, 248, 248));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Fecha:");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 60, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_montoTotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_montoTotalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_montoTotalMouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel7MouseClicked

    private void combo_vehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_vehiculoActionPerformed
        try {
            mostrarTabla();
            mostrarTotal();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_combo_vehiculoActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.setVisible(false);
        UIInfraccion uiI = new UIInfraccion();
        uiI.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void combo_vehiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combo_vehiculoMouseClicked
        
    }//GEN-LAST:event_combo_vehiculoMouseClicked

    private void tablaPagosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPagosMouseClicked
        int datos=tablaPagos.getSelectedRowCount();
        int[] datoss=tablaPagos.getSelectedRows();
        double total=0;
        for (int i = 0; i < datos; i++) {
            double monto=Double.parseDouble((String) tablaPagos.getValueAt(datoss[i], 2));
            total+=monto;
        }
        txt_montoTotal.setText(""+total);
    }//GEN-LAST:event_tablaPagosMouseClicked

    private void txt_fechaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_fechaKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            agregarPago();
        }
    }//GEN-LAST:event_txt_fechaKeyPressed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        agregarPago();
    }//GEN-LAST:event_jLabel3MouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIPagoInfraccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIPagoInfraccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIPagoInfraccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIPagoInfraccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIPagoInfraccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Herramientas.Combobox combo_vehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private Herramientas.PanelRound panelRound3;
    private Herramientas.PanelRound panelRound4;
    private javax.swing.JTable tablaPagos;
    private javax.swing.JTextField txt_fecha;
    private javax.swing.JLabel txt_montoTotal;
    // End of variables declaration//GEN-END:variables

    void run() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
