/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import control.InfraccionJpaController;
import control.InfraccionesJpaController;
import control.VehiculoJpaController;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import modelo.Infraccion;
import modelo.Infracciones;
import modelo.TModeloInfracciones;
import modelo.TModeloVehiculo;
import modelo.Tipovehiculo;
import modelo.Vehiculo;

/**
 *
 * @author Hector
 */
public class UIRegistroInfracciones extends javax.swing.JFrame {

    private InfraccionJpaController cInfraccion;
    private InfraccionesJpaController cInfracciones;
    private VehiculoJpaController cVehiculo;
    private Infraccion infraccion;
    private Vehiculo vehiculo;
    private Infracciones Infracciones;
    private List<Vehiculo> List_Vehiculos;
    private List<Infracciones> List_Infracciones;
    private List<Infraccion> List_Infraccion;
    private TModeloInfracciones modelot;

    /**
     * Creates new form UIRegistroInfracciones
     */
    public UIRegistroInfracciones() {
        initComponents();
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("1ProyectoVehiculoPU");
        cVehiculo = new VehiculoJpaController(emf);
        cInfracciones = new InfraccionesJpaController(emf);
        cInfraccion = new InfraccionJpaController(emf);
        List_Vehiculos = cVehiculo.findVehiculoEntities();
        List_Infracciones = cInfracciones.findInfraccionesEntities();
        List_Infraccion = cInfraccion.findInfraccionEntities();
        modelot = new TModeloInfracciones(List_Infracciones);
        modelot.fireTableDataChanged();
        TablaInfracciones.setModel(modelot);
        cargarPlaca();
        cargarInfraccion();

    }

    private void cargarPlaca() {
        List_Vehiculos = cVehiculo.findVehiculoEntities();
        Combo_Placa.removeAllItems();
        for (Vehiculo vh : List_Vehiculos) {
            Combo_Placa.addItem(vh.getPlaca());
        }
    }

    private void cargarInfraccion() {
        List_Infraccion = cInfraccion.findInfraccionEntities();
        combo_infrac.removeAllItems();
        for (Infraccion inf : List_Infraccion) {
            combo_infrac.addItem(inf.getIdinfraccion());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelRound3 = new Herramientas.PanelRound();
        button_pagar = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panelRound4 = new Herramientas.PanelRound();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaInfracciones = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        combo_infrac = new Herramientas.Combobox();
        Combo_Placa = new Herramientas.Combobox();
        txt_fecha = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(32, 32, 32));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(248, 248, 248));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRO DE INFRACCIONES");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 370, -1));

        panelRound3.setBackground(new java.awt.Color(64, 64, 64));
        panelRound3.setRoundBottomLeft(30);
        panelRound3.setRoundBottomRight(30);
        panelRound3.setRoundTopLeft(30);
        panelRound3.setRoundTopRight(30);

        button_pagar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        button_pagar.setForeground(new java.awt.Color(248, 248, 248));
        button_pagar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        button_pagar.setText("Registrar");
        button_pagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_pagarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(button_pagar, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(button_pagar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(panelRound3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 120, 40));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, 40, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(248, 248, 248));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Fecha");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 100, 40));

        panelRound4.setBackground(new java.awt.Color(54, 54, 54));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(248, 248, 248));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Vehiculo");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(248, 248, 248));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Fecha Pago");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(248, 248, 248));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("IdFolioInf");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(248, 248, 248));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("IdInfracción");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(248, 248, 248));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Fecha Infracción");

        javax.swing.GroupLayout panelRound4Layout = new javax.swing.GroupLayout(panelRound4);
        panelRound4.setLayout(panelRound4Layout);
        panelRound4Layout.setHorizontalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        panelRound4Layout.setVerticalGroup(
            panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(panelRound4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 560, 30));

        TablaInfracciones.setBackground(new java.awt.Color(64, 64, 64));
        TablaInfracciones.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        TablaInfracciones.setForeground(new java.awt.Color(248, 248, 248));
        TablaInfracciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"a", "1", "a", "1", "q"},
                {"b", "2", "b", "2", "w"},
                {"c", "3", "c", "3", "e"},
                {"d", "4", "d", "4", "r"},
                {"e", "5", "e", "5", "t"},
                {"r", "6", "f", "6", "y"},
                {"f", "7", "g", "7", "u"},
                {"g", "8", "h", "8", "i"},
                {"h", "9", "i", "9", "o"},
                {"i", "0", "j", "0", "p"},
                {"j", "1", "k", "1", "a"},
                {"k", "2", "l", "2", null}
            },
            new String [] {
                "", "", "", "", ""
            }
        ));
        jScrollPane1.setViewportView(TablaInfracciones);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 560, 210));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 540, 40, 20));

        combo_infrac.setBackground(new java.awt.Color(34, 34, 34));
        combo_infrac.setForeground(new java.awt.Color(248, 248, 248));
        combo_infrac.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", " " }));
        combo_infrac.setSelectedIndex(-1);
        combo_infrac.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        combo_infrac.setLabeText("Infracción");
        jPanel1.add(combo_infrac, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 350, 50));

        Combo_Placa.setBackground(new java.awt.Color(34, 34, 34));
        Combo_Placa.setForeground(new java.awt.Color(248, 248, 248));
        Combo_Placa.setSelectedIndex(-1);
        Combo_Placa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Combo_Placa.setLabeText("Placa");
        jPanel1.add(Combo_Placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 350, 50));

        txt_fecha.setBackground(new java.awt.Color(248, 248, 248));
        txt_fecha.setForeground(new java.awt.Color(8, 8, 8));
        txt_fecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_fecha.setBorder(null);
        jPanel1.add(txt_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 230, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/antes.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, 40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.setVisible(false);
        UIInfraccion uiI = new UIInfraccion();
        uiI.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void button_pagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_pagarMouseClicked
        Infracciones = new Infracciones();
        Infracciones.setVehiculo(List_Vehiculos.get(Combo_Placa.getSelectedIndex()));
        Infracciones.setInfraccion(List_Infraccion.get(combo_infrac.getSelectedIndex()));
        Infracciones.setFecha(ParseFecha(txt_fecha.getText()));
        Infracciones.setFechapago(ParseFecha("000/00/00"));
        cInfracciones.create(Infracciones);
        modelot.fireTableDataChanged();
        List_Infracciones.add(Infracciones);
    }//GEN-LAST:event_button_pagarMouseClicked

    public static Date ParseFecha(String fecha) {
        SimpleDateFormat formato = new SimpleDateFormat("yyyy/MM/dd");
        Date fechaDate = null;
        try {
            fechaDate = formato.parse(fecha);
        } catch (ParseException ex) {
            System.out.println(ex);
        }
        return fechaDate;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIRegistroInfracciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIRegistroInfracciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIRegistroInfracciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIRegistroInfracciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIRegistroInfracciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Herramientas.Combobox Combo_Placa;
    private javax.swing.JTable TablaInfracciones;
    private javax.swing.JLabel button_pagar;
    private Herramientas.Combobox combo_infrac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private Herramientas.PanelRound panelRound3;
    private Herramientas.PanelRound panelRound4;
    private javax.swing.JTextField txt_fecha;
    // End of variables declaration//GEN-END:variables
}
